name: rapid_mind
description: "Flutter app that combines a math quiz with a fast-paced reaction game for diverse and engaging gameplay."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true